[project]
name = 'chess-protocol'
description = ''
authors = ['Jadonamite']
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.gateway]
path = 'contracts/gateway.clar'
clarity_version = 2
epoch = 'latest'

[contracts.gateway_v2]
path = 'contracts/gateway_v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.chess-token_v2]
path = 'contracts/chess-token_v2.clar'
clarity_version = 4
epoch = 'latest'

